
export default function Privacy() {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-500 mb-4">Last updated: November 06, 2024</p>
      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information
        when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="mb-4">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use
        of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
      
      <h3 className="text-xl font-semibold mt-6 mb-3">Interpretation</h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following
        definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside space-y-3">
          <li><p><strong>Account</strong>: a unique account created for You to access our Service or parts of our Service.</p></li>
          <li><p><strong>Affiliate</strong>: an entity that controls, is controlled by, or is under common control with a party.</p></li>
          <li><p><strong>Application</strong>: jeras.si, the software program provided by the Company.</p></li>
          <li><p><strong>Company</strong>: jeras.si (referred to as "the Company", "We", "Us", or "Our").</p></li>
          <li><p><strong>Country</strong>: United Kingdom</p></li>
          <li><p><strong>Device</strong>: any device that can access the Service such as a computer, a cellphone, or a digital tablet.</p></li>
          <li><p><strong>Personal Data</strong>: any information that relates to an identified or identifiable individual.</p></li>
          <li><p><strong>Service</strong>: the Application.</p></li>
          <li><p><strong>Service Provider</strong>: any natural or legal person who processes the data on behalf of the Company.</p></li>
          <li><p><strong>Usage Data</strong>: data collected automatically, either generated by the use of the Service or from the Service infrastructure.</p></li>
          <li><p><strong>You</strong>: the individual accessing or using the Service.</p></li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>

      <h3 className="text-xl font-semibold mt-6 mb-3">Types of Data Collected</h3>
      
      <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
      <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information, such as:
      </p>
      <ul className="list-disc list-inside space-y-2">
          <li><p>Email address</p></li>
          <li><p>Usage Data</p></li>
      </ul>

      <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
      <p className="mb-4">Usage Data is collected automatically when using the Service and may include information such as:</p>
      <ul className="list-disc list-inside space-y-2">
          <li>Your Device's Internet Protocol address (e.g., IP address)</li>
          <li>Browser type and version</li>
          <li>Pages visited and time spent</li>
          <li>Other diagnostic data</li>
      </ul>

      <h3 className="text-xl font-semibold mt-6 mb-3">Use of Your Personal Data</h3>
      <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc list-inside space-y-3">
          <li><strong>To provide and maintain our Service</strong></li>
          <li><strong>To manage Your Account</strong></li>
          <li><strong>For contract performance</strong></li>
          <li><strong>To contact You</strong></li>
          <li><strong>To provide You with offers and information</strong></li>
          <li><strong>To manage Your requests</strong></li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us by email:</p>
      <ul className="list-disc list-inside">
          <li>By email: matija.jeras64@gmail.com</li>
      </ul>
    </div>
  )
}